AWSTemplateFormatVersion: "2010-09-09"
Description: "A template to create all the Event Processing infrastructure. Currently just a single SNS topic"
Parameters:

Resources:
  epSNSTopic:
    Properties:
      TopicName: !Sub "EventProcessorSNSTopic-${AWS::StackName}"
    Type: "AWS::SNS::Topic"

  # No subscriptions yet

  # No policies yet

  # No Output yet
