version=0.1
[default.deploy.parameters]
stack_name = "di-txma-ep-build"
profile="di-dev-event-processing-admin"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"build\""
parameter_overrides=[
    "Environment=build"
]

[build.deploy.parameters]
stack_name = "di-txma-ep-build"
profile="di-dev-event-processing-admin"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"build\""
parameter_overrides=[
    "Environment=build"
]

[staging.deploy.parameters]
stack_name = "di-txma-ep-staging"
profile="di-dev-event-processing-admin"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"staging\""
parameter_overrides=[
    "Environment=staging"
]

[production.deploy.parameters]
stack_name = "di-txma-ep-production"
profile="di-dev-event-processing-admin"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"production\""
parameter_overrides=[
    "Environment=production"
]

[integration.deploy.parameters]
stack_name = "di-txma-ep-integration"
profile="di-dev-event-processing-admin"
region = "eu-west-2"
tags = "project=\"di-txma-event_processor\" stage=\"integration\""
parameter_overrides=[
    "Environment=integration"
]