AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "A template to create all the Event Processing infrastructure. Currently just a single SNS topic"

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - build
      - staging
      - production
      - integration
    Default: build
    Description: "The current environment for deployment (e.g. build, staging, production, etc.)"

Resources:
  epSNSTopic:
    Properties:
      TopicName: !Sub
        - "EventProcessorSNSTopic-${EnvironmentName}"
        - EnvironmentName: !Ref Environment
    Type: "AWS::SNS::Topic"

  SNSSubscribePolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Id: SNSSubscribePolicy
        Version: 2012-10-17
        Statement:
          - Sid: SNSSubscribePolicy-1
            Effect: Allow
            Action:
              - 'sns:Subscribe'
            Principal:
                AWS:
                  - "arn:aws:iam::725018305812:root"
            Resource: !Ref epSNSTopic
      Topics:
      - !Ref epSNSTopic

Outputs:
  epSNSTopicARN:
    Description: ARN of SNS Topic
    Value: !Ref epSNSTopic
    Export:
      Name: !Sub
        - "${StackName}-SnsArn"
        - StackName: !Ref "AWS::StackName"
