name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  environment: CI
  awsRegion: "eu-west-2"
  eventProcessorDirectory: "event-processing"
  auditDirectory: "audit"

# A workflow to build the event processor and audit infrastructure and deploy to the development (CI) environment
# This may be subject to change if we can make re-usable actions to reference (This will need to be in concert with other GDS DI teams)
jobs:
  validate_and_build_event_processor:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ eventProcessorDirectory }}
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.EVENT_PROCESSING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.EVENT_PROCESSING_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ awsRegion }}
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        working-directory: ${{ eventProcessorDirectory }}/event-processor
        run: npm ci
      - name: SAM Validate
        run: |
          sam validate --template-file event-processing-template.yml --config-file config/samconfig-event-processing.toml --config-env ${{ environment }}
      - name: SAM Build
        run: |
          sam build --template-file event-processing-template.yml --config-file config/samconfig-event-processing.toml --config-env ${{ environment }}
      - name: Test
        working-directory: ${{ eventProcessorDirectory }}/event-processor
        run: npm test
      - run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-file config/samconfig-audit.toml --config-env ${{ environment }} --resolve-s3
        if: github.event_name != 'pull_request'

  validate_and_build_audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ auditDirectory }}
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AUDIT_DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AUDIT_DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ awsRegion }}
      - name: SAM Validate
        run: |
          sam validate --template-file audit-template.yml --config-file config/samconfig-audit.toml --config-env ${{ environment }}
      - name: SAM Build
        run: |
          sam build --template-file audit-template.yml --config-file config/samconfig-audit.toml --config-env ${{ environment }}
      - run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-file config/samconfig-audit.toml --config-env ${{ environment }}
        if: github.event_name != 'pull_request'
          
